@echo off
echo Open Watcom Build Environment
PATH C:\WATCOM2\BINNT64;C:\WATCOM2\BINNT;%PATH%
SET INCLUDE=C:\WATCOM2\H;C:\WATCOM2\H\NT;C:\WATCOM2\H\NT\DIRECTX;C:\WATCOM2\H\NT\DDK;%INCLUDE%
SET WATCOM=C:\WATCOM2
SET EDPATH=C:\WATCOM2\EDDAT
SET WHTMLHELP=C:\WATCOM2\BINNT\HELP
SET WIPFC=C:\WATCOM2\WIPFC
